name: modecl
channels:
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.4
  - python==3.11.11
  - matplotlib
  - conda-forge::pvl
  - ultralytics
  - conda-forge::pycocotools
  - anaconda::sympy
