services:
  mod-cl:
    restart: always
    shm_size: '96gb'
    build: .
    container_name: 'MOD-CL'
    working_dir: '/root'
    tty: true
    volumes:
      - ../:/root/T-NormRL
      - ../../road-dataset:/root/road-dataset
      - ../../ROAD++:/root/ROAD++
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]