path: /root/ROAD++/task4_yolo_roadpp
train: images/train
val: images/val
test:
nc: 48

# Classes (80 COCO classes)
names:
  0: Ped
  1: Car
  2: Cyc
  3: Mobike
  4: MedVeh
  5: LarVeh
  6: Bus
  7: EmVeh
  8: TL
  9: Red
  10: Amber
  11: Green
  12: MovAway
  13: MovTow
  14: Mov
  15: Brake
  16: Stop
  17: IncatLeft
  18: IncatRht
  19: HazLit
  20: TurnLft
  21: TurnRht
  22: Ovtak
  23: Wait2X
  24: XingFmLft
  25: XingFmRht
  26: Xing
  27: PushObj
  28: VehLane
  29: OutgoLane
  30: OutgoCycLane
  31: IncomLane
  32: IncomCycLane
  33: Pav
  34: LftPav
  35: RhtPav
  36: Jun
  37: xing
  38: BusStop
  39: parking
  40: OutgoBusLane
  41: IncomBusLane
  42: rightParking
  43: LftParking
  44: Rev
  45: SmalVeh
  46: MovLft
  47: MovRht
